##################################################
##### TEST / DEVELOPMENT ENVIRONMENT    ##########
##################################################

# Public ports:
#  - 8081 -> Neos
#  - 13306 -> maria db (used for Neos)
#  - 15432 -> postgres db (used for Neos)
services:
  #####
  # Neos CMS (php-fpm)
  neos:
    build:
      context: ..
      dockerfile: ./local-dev/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      #FLOW_CONTEXT: 'Development/Docker/Postgres'
      #KISSEARCH_POSTGRES_LANGUAGE_MODE: 'contentDimension'
      FLOW_CONTEXT: 'Development/Docker/MariaDB'
      COMPOSER_CACHE_DIR: '/composer_cache'
      # DB connection
      MARIA_DB_NEOS_HOST: 'maria-db'
      MARIA_DB_NEOS_PORT: 3306
      MARIA_DB_NEOS_PASSWORD: 'neos'
      MARIA_DB_NEOS_USER: 'neos'
      MARIA_DB_NEOS_DATABASE: 'neos'
      POSTGRES_DB_NEOS_HOST: 'postgres-db'
      POSTGRES_DB_NEOS_PORT: 5432
      POSTGRES_DB_NEOS_PASSWORD: 'neos'
      POSTGRES_DB_NEOS_USER: 'neos'
      POSTGRES_DB_NEOS_DATABASE: 'neos'
    volumes:
      # mount KISSearch source packages
      - ../DistributionPackages/:/DistributionPackages/:cached
      # mount test-distribution
      - ../local-dev-app/:/app/:cached
      # Explcitly set up Composer cache for faster fetching of packages
      - ./tmp/composer_cache:/composer_cache:cached
    networks:
      - kissearch-test-distribution
    ports:
      - '8081:8081'
    depends_on:
      - maria-db
      - postgres-db

  #####
  # Maria DB
  maria-db:
    image: mariadb:11
    ports:
      - '13306:3306'
    networks:
      - kissearch-test-distribution
    environment:
      MYSQL_ROOT_PASSWORD: neos
      MYSQL_DATABASE: neos
      MYSQL_USER: neos
      MYSQL_PASSWORD: neos
    #command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--general-log=1', '--general-log-file=/var/lib/mysql/general-log.log']

  #####
  # Postgres DB
  postgres-db:
    image: postgres:17
    networks:
      - kissearch-test-distribution
    environment:
      POSTGRES_PASSWORD: neos
      POSTGRES_DB: neos
      POSTGRES_USER: neos
    ports:
      - 15432:5432

networks:
  # we need to use a custom network here to ensure that all services see each other
  kissearch-test-distribution:
    name: kissearch-test-distribution
