Sandstorm:
  KISSearch:

    # database type; mainly required for minimal version checking
    # supported databases:
    #  - MySQL
    #  - MariaDB
    #  - PostgreSQL (coming soon)
    databaseType: 'MariaDB'

    schemas:
      # TODO

    query:

      # add sources here
      searchSources:
        # 'my-source':
        #   class: '...'

      # add filters here
      resultFilters:
        # 'my-filter':
        #   class: '...'

      # add type aggregators here
      typeAggregators:
        'default':
          class: 'Sandstorm\KISSearch\Flow\Query\DefaultTypeAggregator'
        # 'my-type':
        #   class: '...'

      # search endpoint configurations
      endpoints:
        # TODO
