Sandstorm:
  KISSearch:

    query:
      endpoints:

        # endpoint ID
        'us-live':
          queryOptions:
            contentRepository: 'default'
          filters:
            # all parameter names are prefixed with this filter identifier
            'neos':
              # required sources
              sources:
                - neos-content-source
              # reference to the implementing PHP class creating the query part
              filter: neos-content-filter
              # result type name
              resultType: neos-document
              # parameter default values
              defaultParameters:
                'workspace': 'live'
                'site_node': 'neosdemo'
                'dimension_values':
                  'language': 'en_US'
                #'exclude_site_node': []
                #'content_node_types': []
                #'document_node_types': []
                #'root_node': '...'
                #'inherited_document_node_type': ''
                #'inherited_content_node_type': ''
          # type aggregators, scoped by their respective result type name
          typeAggregators:
            'neos-document':
              aggregator: neos-document-type-aggregator
